apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cloudflare-repository
  namespace: flux-system
spec:
  interval: 12h
  url: https://cloudflare.github.io/helm-charts
